services:
  loki:
    image: grafana/loki:3.5.5
    ports:
      - "3101:3100"
    volumes:
      - ./loki.yaml:/etc/loki/config.yaml
    command: -config.file=/etc/loki/config.yaml

  alloy:
    image: grafana/alloy:latest
    ports:
      - "3102:12345"
    volumes:
      - ./config.alloy:/etc/alloy/config.alloy
      - ./app.log:/var/log/app.log:ro
    command: run /etc/alloy/config.alloy --server.http.listen-addr=0.0.0.0:12345
    depends_on:
      - loki

  grafana:
    image: grafana/grafana:12.3.0-17782621999
    ports:
      - "3100:3000"
    environment:
      - GF_SECURITY_ADMIN_PASSWORD=admin
    volumes:
      - grafana-storage:/var/lib/grafana
    depends_on:
      - loki

volumes:
  grafana-storage: