// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.29.0

package sqlcdb

import (
	ariand "ariand/gen/go/ariand/v1"
	"github.com/jackc/pgx/v5/pgtype"
	"github.com/shopspring/decimal"
)

type Account struct {
	Id             int64              `json:"id"`
	Name           string             `json:"name"`
	Bank           string             `json:"bank"`
	AccountType    ariand.AccountType `json:"accountType"`
	Alias          *string            `json:"alias"`
	AnchorDate     pgtype.Date        `json:"anchorDate"`
	AnchorBalance  decimal.Decimal    `json:"anchorBalance"`
	AnchorCurrency string             `json:"anchorCurrency"`
	CreatedAt      pgtype.Timestamptz `json:"createdAt"`
	UpdatedAt      pgtype.Timestamptz `json:"updatedAt"`
}

type Category struct {
	Id        int64              `json:"id"`
	Slug      string             `json:"slug"`
	Label     string             `json:"label"`
	Color     string             `json:"color"`
	CreatedAt pgtype.Timestamptz `json:"createdAt"`
	UpdatedAt pgtype.Timestamptz `json:"updatedAt"`
}

type Receipt struct {
	Id             int64                     `json:"id"`
	Engine         ariand.ReceiptEngine      `json:"engine"`
	ParseStatus    ariand.ReceiptParseStatus `json:"parseStatus"`
	LinkStatus     ariand.ReceiptLinkStatus  `json:"linkStatus"`
	MatchIds       []int64                   `json:"matchIds"`
	Merchant       *string                   `json:"merchant"`
	PurchaseDate   pgtype.Date               `json:"purchaseDate"`
	TotalAmount    *decimal.Decimal          `json:"totalAmount"`
	Currency       *string                   `json:"currency"`
	TaxAmount      *decimal.Decimal          `json:"taxAmount"`
	RawPayload     []byte                    `json:"rawPayload"`
	CanonicalData  []byte                    `json:"canonicalData"`
	ImageUrl       *string                   `json:"imageUrl"`
	ImageSha256    []byte                    `json:"imageSha256"`
	Lat            *float64                  `json:"lat"`
	Lon            *float64                  `json:"lon"`
	LocationSource *string                   `json:"locationSource"`
	LocationLabel  *string                   `json:"locationLabel"`
	CreatedAt      pgtype.Timestamptz        `json:"createdAt"`
	UpdatedAt      pgtype.Timestamptz        `json:"updatedAt"`
}

type ReceiptItem struct {
	Id           int64              `json:"id"`
	ReceiptId    int64              `json:"receiptId"`
	LineNo       *int32             `json:"lineNo"`
	Name         string             `json:"name"`
	Qty          *decimal.Decimal   `json:"qty"`
	UnitPrice    *decimal.Decimal   `json:"unitPrice"`
	LineTotal    *decimal.Decimal   `json:"lineTotal"`
	Sku          *string            `json:"sku"`
	CategoryHint *string            `json:"categoryHint"`
	CreatedAt    pgtype.Timestamptz `json:"createdAt"`
	UpdatedAt    pgtype.Timestamptz `json:"updatedAt"`
}

type Transaction struct {
	Id              int64                       `json:"id"`
	AccountId       int64                       `json:"accountId"`
	EmailId         *string                     `json:"emailId"`
	TxDate          pgtype.Timestamptz          `json:"txDate"`
	TxAmount        decimal.Decimal             `json:"txAmount"`
	TxCurrency      string                      `json:"txCurrency"`
	TxDirection     ariand.TransactionDirection `json:"txDirection"`
	TxDesc          *string                     `json:"txDesc"`
	BalanceAfter    *decimal.Decimal            `json:"balanceAfter"`
	Merchant        *string                     `json:"merchant"`
	CategoryId      *int64                      `json:"categoryId"`
	CatStatus       ariand.CategorizationStatus `json:"catStatus"`
	Suggestions     []string                    `json:"suggestions"`
	UserNotes       *string                     `json:"userNotes"`
	ForeignCurrency *string                     `json:"foreignCurrency"`
	ForeignAmount   *decimal.Decimal            `json:"foreignAmount"`
	ExchangeRate    *decimal.Decimal            `json:"exchangeRate"`
	ReceiptId       *int64                      `json:"receiptId"`
	CreatedAt       pgtype.Timestamptz          `json:"createdAt"`
	UpdatedAt       pgtype.Timestamptz          `json:"updatedAt"`
}
